### ISSUE TITLE
cpu占用百分之百

### ISSUE THREAD

**Issue by pandatest2023** [Dliv3/Venom#12]
环境：windows tomcat 
webshell运行agent 端口复用模式 成功连接，停止tomcat后，agent CPU占用百分之百

**Comment by Dliv3** [comment]
admin和agent运行的命令都是什么？

**Comment by pandatest2023** [comment]
> 管理员和代理运行的命令都是什么？

agent.exe -lhost 192.168.x.x -reuse-port 80 
admin -rhost 192.168xx rport 80

**Comment by Dliv3** [comment]
Fixed in commits https://github.com/Dliv3/Venom/commit/5488f8ffa6b97400344ab0a17f7ffe7e218ed71a and https://github.com/Dliv3/Venom/commit/2b84e6846992399edf72eb6375825fc9062b2f01
