### ISSUE TITLE
SOCKS5 DNS 解析问题

### ISSUE THREAD

**Issue by NickYan7** [Dliv3/Venom#16]
很棒的项目，点赞！

另外有一个关于建立了 SOCKS5 连接后 DNS 无法解析的问题。在目标内网起了 agent，端口映射至 VPS，然后外网攻击机 admin 连接 VPS 的端口，建立好连接，起 SOCKS5 服务，在攻击机本地监听了 7777 端口，至此一切正常。

接着浏览器设置代理，代理本地 7777 端口，使攻击机可以访问目标内网的 web 服务，但是以域名访问时无法解析（例 wiki.xxx.com），以目标内网 IP 请求时可以访问，说明 DNS 请求没有通过 SOCKS5 隧道转发至 agent 去请求目标内网的 DNS 服务器。

奇怪了，SOCKS5 不是默认会连带 DNS 请求一起走隧道吗？测试了其他的突破内网访问限制的方式，比如 goagent，ssr 等，都出现了这种问题，求一波解答，感谢！

另外，在以域名访问时，agent 报错如下图：

![venom](https://user-images.githubusercontent.com/27906343/98892890-3f663500-24dc-11eb-851b-084643725751.png)

**Comment by Dliv3** [comment]
socks5协议和该项目的代码实现都允许代理DNS。

一般的socks5客户端都会有一个选项选择是否代理DNS，比如proxychains4有一个proxy_dns的选项，你可以检查一下你的客户端配置是否开启了这个选项

**Comment by NickYan7** [comment]
> socks5协议和该项目的代码实现都允许代理DNS。
> 
> 一般的socks5客户端都会有一个选项选择是否代理DNS，比如proxychains4有一个proxy_dns的选项，你可以检查一下你的客户端配置是否开启了这个选项

感谢答疑！

奇怪就在于，我用该项目 admin 端建立 socks 隧道，本地监听 7777 端口后，浏览器直接用 switchyomega 设置 socks5 代理，理论上 DNS 解析也是带入 agent 端解析的啊，还是说 venom 本地需要做相关配置呢？如果需要的话应该修改哪里？

**Comment by Dliv3** [comment]
venom本地不需要做相关配置，如果你在agent的log中看到的是域名，那就说明dns是在agent端解析的，如果在agent的log中看到的是ip，那就是说明dns是在admin端解析的，你可以按这个方法确认一下dns是否被代理过去了

**Comment by NickYan7** [comment]
> venom本地不需要做相关配置，如果你在agent的log中看到的是域名，那就说明dns是在agent端解析的，如果在agent的log中看到的是ip，那就是说明dns是在admin端解析的，你可以按这个方法确认一下dns是否被代理过去了

了解了，感谢。
