### ISSUE TITLE
CentOS CPU占用 100%

### ISSUE THREAD

**Issue by NickYan7** [Dliv3/Venom#20]
是 Bug 么？agent_linux_x64。
环境 CentOS 云服务器，运行命令 `nohup ./agent_linux_x64 -lport 9898 -passwd xxx &`

![Screenshot 2021-01-21 上午10 14 58](https://user-images.githubusercontent.com/27906343/105271157-fe705800-5bd1-11eb-8ebc-7f4cfcb4f584.jpg)
![Screenshot 2021-01-21 上午10 16 05](https://user-images.githubusercontent.com/27906343/105271170-03cda280-5bd2-11eb-8447-6a2789b7b63b.jpg)

**Comment by NickYan7** [comment]
测试发现如果 nohup 后台运行 agent 的话就会导致 CPU 占满，直接运行 `./agent -lport 9898` 不会占满 CPU。

**Comment by NickYan7** [comment]
老大能加个自动回连机制么？agent 去主动连接 admin，如果 admin 突然掉线 agent 是无法重连的，报 EOF 错误。

**Comment by Dliv3** [comment]
最新的代码修了这个问题，但是没有发release，可以自己clone代码编译。最近正在重构整个项目，重连功能之后会加。

**Comment by NickYan7** [comment]
> 最新的代码修了这个问题，但是没有发release，可以自己clone代码编译。最近正在重构整个项目，重连功能之后会加。

测试有效，感谢。
