### ISSUE TITLE
节点间通信流量使用AES加密

### ISSUE THREAD

**Issue by 00theway** [Dliv3/Venom#4]
通过继承net.Conn实现aes加密
https://github.com/00theway/Venom-crypt

**Comment by Dliv3** [comment]
可以以PR形式提交aes加密部分代码吗

**Comment by Dliv3** [comment]
我觉得可以考虑加一个命令行选项，比如`-pwd`指定aes key

**Comment by Dliv3** [comment]
新版本实现了节点间通信流量加密
代码: [v1.1.0](https://github.com/Dliv3/Venom/tree/v1.1.0) 
可执行文件: [release](https://github.com/Dliv3/Venom/releases/tag/v1.1.0)
