### ISSUE TITLE
断线重连？

### ISSUE THREAD

**Issue by lanybass** [Dliv3/Venom#7]
agent连admin，admin有节点了，很好。
但是我用完之后就退出admin，等两天我还想继续用，我又打开admin，但是agent不会自动练上来，那我岂不是又要跑到agent机器去重启程序？

**Comment by Dliv3** [comment]
暂时没有打算提供断线自动重连功能，之后可能会考虑

**Comment by Dliv3** [comment]
你可以选择从admin正向连接agent

**Comment by lanybass** [comment]
admin在外网，agent在内网,只能agent连出去

**Comment by Dliv3** [comment]
可以在外网再放一台agent，让内网的agent连它

**Comment by lanybass** [comment]
已实现，已提交pull request  
因为外网的agent机器也可能有时需要重启，不想每次断开了就让内网的人去重开程序，所以还是需要自动重连才行。
